language: cpp
sudo: required
dist: trusty
compiler:
- gcc
  addons:
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-4.9', 'valgrind']
  env: CXX=g++-4.9
os:
- linux

before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get -qq update
- sudo apt-get install -y libsqlite3-dev libboost-all-dev libdbus-1-dev automake autoconf cmake netcat-openbsd

install: travis_scripts/install_gtest_gmock.sh

before_script: true

script: travis_scripts/build_script.sh

after_success: true

