language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: 
        - CXX_COMPILER=g++-5
        - CC_COMPIELR=gcc-5

before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get -qq update
- sudo apt-get install -y libsqlite3-dev libboost-all-dev libdbus-1-dev automake autoconf cmake netcat-openbsd valgrind
- sudo apt-get install -y python-pip python-virtualenv
- sudo pip install tox
- sudo pip install -U setuptools six

install: travis_scripts/install_gtest_gmock.sh

before_script: true

script: travis_scripts/script.sh

after_success: true

